Json
ValueType
CommentPlacement
PrecisionType
using Json::Int = int
using Json::UInt = unsigned int
using Json::Int64 = __int64
using Json::UInt64 = unsigned __int64
using Json::LargestInt = Int64
using Json::LargestUInt = UInt64
using Json::Allocator = typename std::conditional< 0 , SecureAllocator<T>, std::allocator<T>>::type
using Json::String = std::basic_string<char, std::char_traits<char>, Allocator<char>>
using Json::IStringStream = std::basic_istringstream<String::value_type, String::traits_type, String::allocator_type>
using Json::OStringStream = std::basic_ostringstream<String::value_type, String::traits_type, String::allocator_type>
using Json::IStream = std::istream
using Json::OStream = std::ostream
using Json::ArrayIndex = unsigned int
using Json::CharReaderPtr = std::auto_ptr<CharReader>
using Json::UIntToStringBuffer = char[uintToStringBufferSize]
using Json::StreamWriterPtr = std::auto_ptr<StreamWriter>
const char Json::hex2[][]
Referenced by toHex16Bit.
bool Json::operator==(const SecureAllocator< T > &, const SecureAllocator< U > &)
Referenced by Json::Value::Value.
bool Json::operator!=(const SecureAllocator< T > &, const SecureAllocator< U > &)
Referenced by Json::Value::Value.
bool Json::parseFromStream(CharReader::Factory const &, IStream &, Value *root, String *errs)
References Json::CharReader::Factory::newCharReader.
Referenced by operator>>.
IStream & Json::operator>>(IStream &, Value &)
References parseFromStream.
Json::__declspec(noreturn) void throwRuntimeError(String const &msg)
void Json::swap(Value &a, Value &b)
References swap, Json::Value::swap.
Referenced by swap, Json::Value::Value, Json::Value::Value.
String Json::writeString(StreamWriter::Factory const &factory, Value const &root)
References Json::StreamWriter::Factory::newStreamWriter.
Referenced by Json::Value::toStyledString.
String Json::valueToString(Int value)
References valueToString.
Referenced by Json::Value::asString, valueToString, valueToString, valueToString, Json::BuiltStyledStreamWriter::writeValue, Json::FastWriter::writeValue, Json::StyledStreamWriter::writeValue, Json::StyledWriter::writeValue.
String Json::valueToString(UInt value)
References valueToString.
String Json::valueToString(LargestInt value)
References Json::Value::maxLargestInt, Json::Value::minLargestInt, uintToString.
String Json::valueToString(LargestUInt value)
References uintToString.
String Json::valueToString(double value, unsigned int precision=Value::defaultRealPrecision, PrecisionType precisionType=PrecisionType::significantDigits)
References valueToString.
String Json::valueToString(bool value)
String Json::valueToQuotedString(const char *value)
References valueToQuotedStringN.
Referenced by Json::StyledStreamWriter::writeValue, Json::StyledWriter::writeValue.
String Json::valueToQuotedString(const char *value, size_t length)
References valueToQuotedStringN.
OStream & Json::operator<<(OStream &, const Value &root)
References Json::StreamWriterBuilder::newStreamWriter.
static char Json::getDecimalPoint()
Referenced by fixNumericLocaleInput.
static String Json::codePointToUTF8(unsigned int cp)
Referenced by Json::OurReader::decodeString, Json::Reader::decodeString.
static void Json::uintToString(LargestUInt value, char *&current)
Referenced by valueToString, valueToString.
Iter Json::fixNumericLocale(Iter begin, Iter end)
Referenced by Json::anonymous_namespace{json_writer.cpp}::valueToString.
void Json::fixNumericLocaleInput(Iter begin, Iter end)
References getDecimalPoint.
Iter Json::fixZerosInTheEnd(Iter begin, Iter end, unsigned int precision)
Referenced by Json::anonymous_namespace{json_writer.cpp}::valueToString.
static std::unique_ptr< T > Json::cloneUnique(const std::unique_ptr< T > &p)
Referenced by Json::Value::Comments::Comments, Json::Value::Comments::operator=.
static bool Json::InRange(double d, T min, U max)
Referenced by Json::Value::asInt, Json::Value::asInt64, Json::Value::asUInt, Json::Value::asUInt64, Json::Value::isConvertibleTo.
static char * Json::duplicateStringValue(const char *value, size_t length)
References Json::Value::maxInt.
static char * Json::duplicateAndPrefixStringValue(const char *value, unsigned int length)
References JSON_ASSERT_MESSAGE, Json::Value::maxInt.
Referenced by Json::Value::dupPayload, Json::Value::Value, Json::Value::Value, Json::Value::Value.
static void Json::decodePrefixedString(bool isPrefixed, char const *prefixed, unsigned *length, char const **value)
Referenced by Json::Value::asCString, Json::Value::asString, Json::Value::dupPayload, Json::Value::getString, Json::Value::operator<, Json::Value::operator==.
static void Json::releasePrefixedStringValue(char *value)
Referenced by Json::Value::releasePayload.
static void Json::releaseStringValue(char *value, unsigned)
static bool Json::IsIntegral(double d)
References IsIntegral.
Referenced by Json::Value::isInt, Json::Value::isInt64, IsIntegral, Json::Value::isIntegral, Json::Value::isUInt, Json::Value::isUInt64.
static bool Json::doesAnyCharRequireEscaping(char const *s, size_t n)
Referenced by valueToQuotedStringN.
static unsigned int Json::utf8ToCodepoint(const char *&s, const char *e)
Referenced by valueToQuotedStringN.
static String Json::toHex16Bit(unsigned int x)
References hex2.
Referenced by appendHex.
static void Json::appendRaw(String &result, unsigned ch)
Referenced by valueToQuotedStringN.
static void Json::appendHex(String &result, unsigned ch)
References toHex16Bit.
Referenced by valueToQuotedStringN.
static String Json::valueToQuotedStringN(const char *value, size_t length, bool emitUTF8=false)
References appendHex, appendRaw, doesAnyCharRequireEscaping, utf8ToCodepoint.
Referenced by valueToQuotedString, valueToQuotedString, Json::BuiltStyledStreamWriter::writeValue, Json::FastWriter::writeValue, Json::StyledStreamWriter::writeValue, Json::StyledWriter::writeValue.